name: Format

on:
  pull_request:
    branches: [main]
    paths:
      - '**.py'

jobs:
  autoyapf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python formatter
        run: |
          python -m pip install --upgrade pip
          pip install autopep8

      - name: Create directory for report
        run: mkdir -p ./post_traces

      - name: Run Autopep8 and save diff report
        run: |
          autopep8 --diff ./*.py > ./post_traces/autopep8_report.txt
          cat post_traces/autopep8_report.txt
