name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['7.0']
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install pytest-cov
          pip install -r requirements.txt
          echo requirements installed
      - name: Cleanup MongoDB container
        run: |
          if [ "$(docker ps -aq -f name=mongodb)" ]; then
            docker rm -f mongodb || true
          fi
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Run tests
        run: |
          python application.py &
          sleep 5
          {
            # Start the test command in the background
            python -m unittest tests.test_module &
            test_pid=$!

            sleep 10

            if ps -p $test_pid > /dev/null; then
              kill $test_pid  # Terminate the background process
              exit_code=0     # Treat the timeout as a pass
            else
              wait $test_pid  # Wait for the process to finish and get the exit code
              exit_code=$?    # Capture the exit code
            fi

            exit $exit_code
          }
